### ISSUE TITLE
New HF radar aggregations submitted to IOOS Registry

### ISSUE THREAD

**Issue by robragsdale** [ioos/registry#76]
There is a new set of Hf radar aggregations available at http://hfrnet.ucsd.edu/thredds/fmrc-catalog.html.  Do you think you could check the data sets listed above to see if they work better with your service? Tom Cook will be upgrading all of our datasets to the FMRC aggregations soon.

Recap of email thread: 
Slowness issues have been occurring for the past few months, and Scripps is trying a different configuration of TDS server to try to improve.  The suggested TDS methods are not working and they are moving to a new aggregation type.  The new set of aggregations are available at http://hfrnet.ucsd.edu/thredds/fmrc-catalog.html.

**Comment by robragsdale** [comment]
@tomcook the new aggregated HF radar services are registered here https://www.ngdc.noaa.gov/docucomp/collectionSource/list?recordSetId=6338758&componentId=&serviceType=&serviceStatus=SUBMITTED&serviceUrl=&search=List+Collection+Sources.

**Comment by robragsdale** [comment]
New aggregated HF radar services approved in [registry](https://www.ngdc.noaa.gov/docucomp/collectionSource/list?recordSetId=6338758&componentId=&serviceType=&serviceStatus=&serviceUrl=&search=List+Collection+Sources).

**Comment by lukecampbell** [comment]
@robragsdale I just looked at it and now it looks like the URLs registered don't point to any valid datasets anymore. Is there anyway we can have the URLs updated in geoportal?

**Comment by rsignell-usgs** [comment]
These FMRC aggregations work great, but I think they are not showing up because the NGDC thredds catalog crawler does not follow `<catalogRef>` entries and since http://hfrnet.ucsd.edu/thredds/fmrc-catalog.html was harvested, and **only** contains `<catalogRef> entries, nothing is coming up.

There are at least 4 ways to solve the problem:
1. modify the NGDC code to follow <catalogRef> entries (but @amilan17 has previously argued against this)
2. Register the 20 children catalogs instead (for example, at this level: 
http://hfrnet.ucsd.edu/thredds/catalog/HFR/USWC/500m/hourly/RTV/catalog.html
http://hfrnet.ucsd.edu/thredds/catalog/HFR/USWC/1km/hourly/RTV/catalog.html
...
3. Ask UCSD to create a new catalog that has these 20 datasets without using <catalogRef>
4. Ask UCSD to run ncISO and create their own WAF, and harvest that.

**Comment by lukecampbell** [comment]
FWIW, I like the WAF approach. It's served me well for GliderDAC and now MARACOOS.

**Comment by rsignell-usgs** [comment]
@lukecampbell , I guess since all these datasets have ISO services, I guess anyone already running https://pypi.python.org/pypi/thredds_crawler could just add
http://hfrnet.ucsd.edu/thredds/fmrc-catalog.html
to the list of thredds catalogs they are harvesting.

**Comment by rsignell-usgs** [comment]
Actually, I guess this crawler: https://github.com/axiom-data-science/thredds_iso_harvester

**Comment by robragsdale** [comment]
Fixed service URLs. Registry URL: https://www.ngdc.noaa.gov/docucomp/collectionSource/list?recordSetId=6338758&componentId=&serviceType=&serviceStatus=&serviceUrl=&search=List+Collection+Sources
