### ISSUE TITLE
GliderDAC WAF cleanout

### ISSUE THREAD

**Issue by lukecampbell** [ioos/registry#80]
Could I get a WAF cleanout?

**Comment by robragsdale** [comment]
@amilan17 can you cleanout the GliderDAC WAF? Thanks.

**Comment by amilan17** [comment]
The Glidar DAC is cleaned out everynight automatically, because the
metadata is harvested from a WAF. (versus THREDDS).
There is a possibility the clean out is not working properly - and it looks
like the count of records doubled last night!

Are you seeing old records in EMMA at:
http://www.ngdc.noaa.gov/metadata/published/NOAA/IOOS/Glider_DAC/iso/



Anna
*~~~~~~Metadata Adds Meaning.~~~~~~*
Anna.Milan@noaa.gov, 303-497-5099
NOAA National Centers for Environmental Information
formerly NOAA’s National Geophysical Data Center
http://www.ngdc.noaa.gov/metadata/emma
*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*

**Comment by lukecampbell** [comment]
So, I don't see the old records in there but I do see them on geoportal
http://www.ngdc.noaa.gov/geoportal/rest/find/document?rid=local&ridName=NOAA%27s%20Geophysical%20Data%20Center&searchText=sys.siteuuid:%22{2546E50F-F0C7-4365-9D45-694DD22E5F26}%22&start=1&max=100&orderBy=relevance&maxSearchTimeMilliSec=10000&f=pjson
and that's what catalog is harvesting. Same goes with MARACOOS.

**Comment by lukecampbell** [comment]
just search "gichigami" or "nokomis"

**Comment by amilan17** [comment]
I manually deleted all records from Geoportal and reharvested. I think it's
looking better now. However, please let me know as soon as this happens
again - 'full synchronization' may not be working as expected.

Anna
*~~~~~~Metadata Adds Meaning.~~~~~~*
Anna.Milan@noaa.gov, 303-497-5099
NOAA National Centers for Environmental Information
formerly NOAA’s National Geophysical Data Center
http://www.ngdc.noaa.gov/metadata/emma
*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*

**Comment by lukecampbell** [comment]
Looks good now, thank you so much.
