### ISSUE TITLE
CSW search  cannot find NDBC nor CO-OPS data

### ISSUE THREAD

**Issue by ocefpaf** [ioos/registry#90]
I checked the SECOORA logs and I noticed that I could not find CO-OPS data automatically, via csw search, during my weekly runs for the whole year of 2015.

NDBC data seems to be missing as well, but we could find data a few weeks ago.

For more on this see: https://github.com/ocefpaf/sscsw/issues/1

**Comment by robragsdale** [comment]
@ocefpaf the NDBC data should be back in the NGDC geoportal.  Sorry for the inconvenience that I think was caused when we did some maintenance on on the NDBC WAF at NGDC.  Please let me know if still cannot find the data.

**Comment by ocefpaf** [comment]
Thanks @robragsdale!  NDBC is OK.  I am still debugging CO-OPS though.  Not sure what is going on there.

**Comment by emiliom** [comment]
@ocefpaf, I think the remaining problem(s) with CO-OPS are much narrower than the original intent of this issue (ie, NDBC and COOPS were both missing from the NGDC GeoPortal and CSW queries!). I would suggest closing this issue and, after some research/debugging (as you're doing now), opening a new narrower issue.

AFAIK, the remaining COOPS problems are:
- The specific CSW query you're doing [here](https://github.com/ocefpaf/sscsw/blob/master/IOOS_data_demo.ipynb) doesn't return the COOPS SOS endpoint, but it should. As I documented on [my notebook](https://github.com/emiliom/stuff/blob/master/IOOS_CSW_NANOOS_and_OOIbbox_tests.ipynb), that's *probably* due to an improper setup for the temporal extent in the COOPS SOS' ISO metadata record. Probably. Definitely needs to be looked into, and may indeed be a Registry issue.
- The pyoos COOPS collector isn't working? I can't remember the status of that, but assuming it's still a problem, it wouldn't be a Registry issue.

I hope that helps.

**Comment by ocefpaf** [comment]
> I would suggest closing this issue and, after some research/debugging (as you're doing now), opening a new narrower issue.

The issue is closed.  I will open a new one as soon as I get back to this.  (Right now I am back to SECOORA.)
